import type { Metadata } from 'next'
import { Quicksand } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/themes/theme-provider'

const quicksand = Quicksand({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  display: 'auto',
})

export const metadata: Metadata = {
  title: 'Echo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang='en'
      suppressHydrationWarning
    >
      <body className={`${quicksand.className} antialiased h-full `}>
        <ThemeProvider
          attribute='class'
          defaultTheme='dark'
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
